tests:
	cd usersim;make

test:
	#cd usersim;make test
	echo "tests completed"

clean:
	rm -f testreport.txt
	cd usersim;make clean

packageqa:
	cd usersim;make packageqa
	cd phonebookqa;make packageqa
