packageqa:
	mkdir -p ../../tmp/phonebookqa/test/phonebookqa
	cp pbqa.sh *.json ../../tmp/phonebookqa/test/phonebookqa/
	@echo "*** Packaging completed in phonebookqa ***"
secure:
	@rm -f config.json confdev.json confprod.json
