tools:
	cd pbsetpw;make
	cd pbsetrole;make
	cd pbsetusername;make
	cd pbadduser;make

clean:
	cd pbsetpw;make clean
	cd pbsetrole;make clean
	cd pbsetusername;make clean
	cd pbadduser;make clean


package:
	cd pbsetpw;make package
	cd pbsetrole;make package
	cd pbsetusername;make package
	cd pbadduser;make package

test:
	cd pbsetpw;make test
	cd pbsetrole;make test
	cd pbsetusername;make test
	cd pbadduser;make test
