db:
	cd schema; make
	cd jobtitles; make
	cd departments; make
	cd roleinit; make
	cd deductions; make
	echo "./dbtools  done."

clean:
	cd schema;make clean
	cd jobtitles;make clean
	cd departments;make clean
	cd roleinit;make clean
	cd deductions; make clean
	echo "./dbtools: clean done."

package:
	cd schema;make package
	cd jobtitles;make package
	cd departments;make package
	cd roleinit;make package
	cd deductions; make package
	echo "./dbtools: package done."

test:
	cd schema;make test
	cd jobtitles;make test
	cd departments;make test
	cd roleinit;make test
	cd deductions; make test
	echo "./dbtools: test done."
