.TH pbupdateallpw 1 "December 23, 2015" "Version 0.9" "USER COMMANDS"
.SH NAME
pbupdateallpw \- set the password for all users in the Accord system
.SH SYNOPSIS
.B pbupdateallpw
[\fB\-B\fR \fIdatabase_username\fR]
[\fB\-help\fR]
[\fB\-N\fR \fIdatabase_name\fR]
[\fB\-p\fR \fIpasswd\fR]

.SH DESCRIPTION
.B pbupdateallpw
sets the user password for all users in the database. This is primarily used for testing. Note
that because the impact of this command could be devastating to a production
installation, the default database name is 
.B accordtest.
This is to ensure that if it applies to the production database that an extra, overt
action must be taken.

.SH OPTIONS
.TP
.IP "-B database_username"
Username for logging into the database server. Default name is "ec2-user"
.IP "-N database_name"
The current default name is accordtest. The production database name is accord.
.IP "-help"
List the options to stdout.
.IP "-p password"
Specifies the new password for all users.

.SH EXAMPLES

.IP "pbupdateallpw -p easy"
This command sets the password for all users  to "easy".

.IP "pbupdateallpw -help"
This command prints the program options to stdout.

.SH BUGS
No known bugs.

.SH AUTHOR
Steve Mansour (sman@accordinterests.com)
.SH "SEE ALSO"
.BR pbadduser (1),
.BR pbsetpw (1),
.BR pbsetrole (1),
.BR pbsetusername (1)