.TH pbwatchdog 1 "December 23, 2015" "Version 0.9" "USER COMMANDS"
.SH NAME
pbwatchdog \- run the Accord System watchdog process
.SH SYNOPSIS
.B pbwatchdog

.SH DESCRIPTION
.B pbwatchdog(1)
monitors a running Phonebook service. If the service goes down the watchdog
process will restart it using the activate(1) process. Phonebook's activate
process will automatically start the watchdog when it performs a START and
will automatically stop the watchdog when it performs a STOP.

Currently, pbwatchdog also initiates database backups. The current data-only
backups are scheduled for 08:15:00 UTC daily. Full backups are scheduled every
Saturday at 08:15:00.

Daily backup database files are stored in the Artifactory directory:

.IP <dbname>/db/<DOM>/<dbname>db.sql.gz

.PP
where <dbname> is the name of the database. This is "accord" by default.
<DOM> is the day-of-the-month as obtained from date(1). The daily backups
are data only. Full database backups are done weekly on Saturdays.

.SH OPTIONS
.TP
none at this time

.SH EXAMPLES

.IP pbwatchdog
Run the watchdog. No params are necessary


.SH BUGS
No known bugs.

.SH AUTHOR
Steve Mansour (sman@accordinterests.com)
.SH "SEE ALSO"
.BR pbrestore (1)
