#!/bin/bash
MAJVER=1
MINVER=0
BLDNOFILE="./buildno"
BUILDNO=$(cat ${BLDNOFILE})
BUILDNO=$((BUILDNO + 1))
FNAME="ver.go"
VER=$(printf "%d.%d.%06d" ${MAJVER} ${MINVER} ${BUILDNO})
DAT=$(date)
cat >${FNAME} <<ZZ1EOF
package lib
// THIS FILE IS AUTOGENERATED
// DO NOT EDIT

// GetVersionNo returns the current version of the server
func GetVersionNo() string { return "${VER}" }
// GetBuildTime returns the date/time the servers code was built
func GetBuildTime() string { return "${DAT}" }
ZZ1EOF
echo "${BUILDNO}" >${BLDNOFILE}
