.TH pbbkup 1 "December 23, 2015" "Version 0.9" "USER COMMANDS"
.SH NAME
pbbkup \- back up the Accord System database
.SH SYNOPSIS
.B pbbkup
[\fB\-f\fR ]
[\fB\-help\fR ]
[\fB\-N\fR \fIdatabase_name\fR]

.SH DESCRIPTION
.B pbbkup
make a full or data-only backup of the Accord System database. Backups are
stored in Artifactory under the path of the form
.B (databaseName)/db/01/(databaseName)db.sql.gz.  For example, the default
database is named "accord", so the file path for data-only backups would be
.B accord/db/01/accorddb.sql.gz.
The number in the path will range from 01 to 31 and represents the day of 
the month on which the backup was done. For example, a backup made on
Jan 05 will be storedin accord/db/05/accorddb.sql.gz.  This backup will be
kept until Feb 05. When a backup is made on Feb 05, the new backup will overwrite
the file in the path accord/db/05. 
.B pbbkup
stores full backups in a path of the form 
.B (databaseName)/db/(databaseName)db.tar.
Every full update overwrites the previous one.
.B date(1).
If it happens to be the first day of the month, an additional copy of the
data-only backup is created in (databaseName)/db/monthly/(databaseName)db.sql.gz.
So, for the "accord" database, it would be accord/db/monthly/accorddb.sql.gz.
.SH OPTIONS
.TP
.IP "-B database_username"
Username for logging into the database server. Default name is "ec2-user"
.IP "-f"
Back up both the data in the database as well as the pictures of individuals.
If this option is not specified, only the data in the database is saved.
.IP "-help"
Lists the command options to stdout.
.IP "-N database_name"
The default name for the production database is "accord".  For testing the
standard name is "accordtest".

.SH EXAMPLES

.IP "pbbkup -f"
Performs a full database backup which includes the people pictures.

.IP "pbbkup"
Performs a data-only database backup.

.SH BUGS
No known bugs.

.SH AUTHOR
Steve Mansour (sman@accordinterests.com)
.SH "SEE ALSO"
.BR pbrestore (1),
