package ws
// THIS FILE IS AUTOGENERATED
// DO NOT EDIT

// GetVersionNo returns the current version of the server
func GetVersionNo() string { return "1.0.000002" }
// GetBuildTime returns the date/time the servers code was built
func GetBuildTime() string { return "Tue Dec  5 12:54:18 PST 2017" }
